<a href="https://colab.research.google.com/github/K0SATIN/Numpy_solutions/blob/FromColab/numpy_solutions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print('Сколько уже можно тянуть, давай начнём!')

In [ ]:
import numpy as np
def array_output(a):
  print()
  print(a)

In [ ]:

a = np.zeros(10)
b = np.ones(10)
c = np.full(10, 5)
d = np.arange(10, 50)
e = np.arange(10, 50, 2)
f = np.arange(0, 9)
f.resize(3,3)
g = np.random.random()
h = np.random.normal(0, 1, 15)
i = np.arange(0.01, 1+0.01, 0.01)
i.resize(10,10)

part_1 = np.array([a,b,c,d,e,f,g,h,i])
for i in part_1:
  array_output(i)



[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]

[5 5 5 5 5 5 5 5 5 5]

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]

[[0 1 2]
 [3 4 5]
 [6 7 8]]

0.23837687504231253

[ 1.00996378  0.17350593 -0.94677107 -1.28124821  1.49187844 -0.99326014
  0.41565338  0.88932557  0.29109731 -0.87057968  0.16104002 -0.57692084
 -0.71210242 -2.05219564  0.30858419]

[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92

<ipython-input-7-fea4c61d1c1e>:13: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  part_1 = np.array([a,b,c,d,e,f,g,h,i])


In [ ]:
mat = np.arange(1,26).reshape(5,5)
array_output(mat)
array_output(mat[2:, 1:])
array_output(mat[3, 4])
array_output(mat[:3, 1])
array_output(mat[4:, :])
array_output(mat[3:, :])
array_output(mat.sum())
array_output(np.std(mat))
array_output(mat.sum(axis = 0))


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

[[12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]

20

[ 2  7 12]

[[21 22 23 24 25]]

[[16 17 18 19 20]
 [21 22 23 24 25]]

325

7.211102550927978

[55 60 65 70 75]
